### PR TITLE
161 fix join space from dashboard space card modal

### LINKED ISSUE #161: Fix join space bug from dashboard
Issue: Error adding user to an existing space when joining from dashboard. 

Steps to reproduce:
image

Expected Behaviour: 
image

### PR DESCRIPTION
**Pull request by eden-chan**
closes #161

### CODE REVIEW

File: components/Dashboard/Cards/SpaceCardModal.js [hunk 1]
```diff
@@ -94,9 +94,10 @@ const SpaceCardModal = ({ handleClose, open, children, friends, participants, ho
 
   const joinSpace = async () => {
     // Add client to participant list
+    console.debug('clien from joinSpace:', client);
```
Comment (LemonFace0309) [inline components/Dashboard/Cards/SpaceCardModal.js:97]: you can probably delete this console debug since it's not very useful

File: utils/getUser.js [hunk 2]
```diff
@@ -3,8 +3,9 @@ import { getSession } from 'next-auth/client';
 import { GET_USER } from '@/utils/apollo/templates/User';
 import { initializeApollo } from '@/utils/apollo/client';
 
-const getUser = async () => {
-  const userSession = await getSession();
+const getUser = async (req) => {
+  // req has to be in an object for getSession to work
```
Comment (LemonFace0309) [inline utils/getUser.js:7]: delete comment

File: utils/getUser.js [hunk 3]
```diff
@@ -3,8 +3,9 @@ import { getSession } from 'next-auth/client';
 import { GET_USER } from '@/utils/apollo/templates/User';
 import { initializeApollo } from '@/utils/apollo/client';
 
-const getUser = async () => {
-  const userSession = await getSession();
+const getUser = async (req) => {
```
Comment (LemonFace0309) [inline utils/getUser.js:6]: oh true. This is only applicable for server side code. Can you do `req = null` so it works without a parameter?

**Review by LemonFace0309 — CHANGES_REQUESTED** [review]

File: utils/getUser.js (hunk 3 above)
Comment (LemonFace0309) [reply utils/getUser.js:6]: or if it works now with the existing code that use getUser then you don't have to change it. I think context/spaces/index.js uses it.

Comment (eden-chan) [reply utils/getUser.js:6]: getUser without anything passed in still works in context/spaces/index.js but in /dashboard it returns undefined if req isn't passed in

**Review by LemonFace0309 — APPROVED** [review]
LGTM
