### PR TITLE
135 fix spotify bugs

### LINKED ISSUE #135: fix spotify bugs
- [ ] move login button to individual room page instead of /room

### PR DESCRIPTION
**Pull request by LemonFace0309**
refactored shopify logic to enable signup within the space instead of outside the space. closes #135 
* added new loading/authenticated/unauthenticated enums
* calls spoitfyAuthURL to authenticate user
* handles backend logic at /api/spotify/login
* sets cookie in res header + additional data in query params
* sets appropriate recoil state client side
* window location replace to remove query url
image
- cleaned up some ui issues in the call tabs.

let me know if you think I should add documentation for certain parts of the pr.

### CODE REVIEW

File: components/Spaces/CallTabs/Music/SpotifySignUpBlocker.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        </Button>
+      )}
+    </Backdrop>
+  );
+};
+
+SpotifySignUpBlocker.propTypes = {
+  loading: PropTypes.bool.isRequired,
+};
+
```
Comment (mabelene) [inline components/Spaces/CallTabs/Music/SpotifySignUpBlocker.js:50]: ye boiii it works
image
image

**Review by mabelene — APPROVED** [review]
had the same bugs you mentioned in the meeting, other than that LGTM 💯
